# Generated by Django 2.1.5 on 2020-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200516_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auther_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog/auther/'),
        ),
    ]
